@startuml
left to right direction 
actor "사용자" as fc
rectangle surver {
 usecase "회원가입" as uc1
 usecase "로그인" as uc2
 usecase "로그아웃" as uc3
 usecase "게임시작" as uc4
 usecase "개인기록"as uc5
 usecase "게임중지" as ac1
 usecase "이스터에그" as ac2
 usecase "게임 스테이지" as ac3
}

fc --> uc1
fc --> uc2
fc --> uc3
fc --> uc4
fc --> uc5
uc4 --> ac1
uc5 --> ac2
uc5 --> ac3

@enduml