@startuml
(*) --> "사용자 입력" 
if "입력중" then
-->"사용자 정보 확인"
if "확인중" then
-->"저장된 스테이지"
if "가는중"then
 --> "stage1"
-->"이야기 전개1"
-->"좀비 전투"
-->"체력회복"
-->"게임을 계속 하고 싶은가?"
else 
-->"stage2"
-->"힌트 획득"
-->"이야기 전개2"
-->"게임을 계속 하고 싶은가?"
else 
-->"stage3"
-->"퀴즈풀기"
-->"중간보스 전투"
-->"체력 회복"
-->"게임을 계속 하고 싶은가?"
if "선택" then
-left->"저장된 스테이지"
else
-->"No"
endif

else 
-->"stage4"
-->"힌트 얻기"
-->"엔딩 이야기 전개"
-->"저장된 스테이지"

endif

  else
 --> "저장된 이스터에그"
 --> "범인 관련된 힌트"

@enduml