@startuml
participant User

User --> System : 캐릭터 불러오기
activate System

System --> Information : 캐릭터 확인
activate Information

System --> User : 캐릭터 생성
deactivate User

System --> Information :  결과
activate Information

User --> System : 게임 시작
activate System

System --> Information : Stage 저장
activate Information

Information --> System : 결과
deactivate Information

System --> Information : 이스터에그 저장
activate Information

Information --> System : 결과
deactivate Information

System --> User : 게임 결과
deactivate User

@enduml